artprima_prometheus_metrics:
    namespace: MetricsApp

    # metrics backend
    storage:
        # Known values: in_memory, apcu, apcng, redis
        type: '%env(PROM_METRICS_TYPE)%'

        host: '%env(PROM_METRICS_HOST)%'
        port: '%env(int:PROM_METRICS_PORT)%'
        timeout: 0.1
        read_timeout: 10
        persistent_connections: false
#        password: '%env(PROM_METRICS_PASSWORD)%'

    ignored_routes:
        - prometheus_bundle_prometheus
        - _wdt

    # used to disable default application metrics
    #disable_default_metrics: false

    # Recommended to disable default metrics from promphp/prometheus_client_php
    # see https://github.com/PromPHP/prometheus_client_php/issues/62
    disable_default_promphp_metrics: true

    # used to enable console metrics
    #enable_console_metrics: false

when@test:
    artprima_prometheus_metrics:
        storage: in_memory
