controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_metrics:
    path: /metrics
    controller: Artprima\PrometheusMetricsBundle\Controller\MetricsController::prometheus